import Flynn
import Foundation
import Socket

open class UserSession: Actor, Equatable {
    // In Picaroon, a user sessions encapsulates on browser's "session" with the server. So when
    // the clinet connects for the very first time, a unique user session is created and assigned
    // to the connection. A cookie is used to store the user session uuid, so it is for multiple
    // connections to utilize the same user session.

    // UserSessions are intented to be subclassed by the application code

    // unsafeSessionUUID is a UUID assigned to this session. It is in intended to be stored and
    // retrieved using HttpOnly cookies

    // unsafeWindowUUID is a UUID also assigned to this session. It is set as the cookie Window-Id
    // and its purpose is to help identify the specific window this session is associated with.
    // Javascript on the client side should store this value in HTML5 sessionStorage and then
    // send it back an http header Window-Id.

    public static func == (lhs: UserSession, rhs: UserSession) -> Bool {
        return lhs.unsafeCombinedSessionUUID == rhs.unsafeCombinedSessionUUID
    }

    let unsafeSessionUUID: String
    let unsafeWindowUUID: String
    public let unsafeCombinedSessionUUID: String

    public var unsafeSessionHeaders: [String] = []

    required public override init() {
        unsafeSessionUUID = UUID().uuidString
        unsafeWindowUUID = UUID().uuidString
        unsafeCombinedSessionUUID = unsafeSessionUUID + unsafeWindowUUID
        super.init()
    }

    open func safeHandleRequest(_ connection: AnyConnection, _ httpRequest: HttpRequest) {
        connection.beSendInternalError()
    }

    private func _beHandleRequest(_ connection: AnyConnection, _ httpRequest: HttpRequest) {
        safeHandleRequest(connection, httpRequest)
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension UserSession {

    @discardableResult
    public func beHandleRequest(_ connection: AnyConnection,
                                _ httpRequest: HttpRequest) -> Self {
        unsafeSend { self._beHandleRequest(connection, httpRequest) }
        return self
    }

}
